apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-demo-playjava
  labels:
    app: k8s-docker-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-docker-demo
  template:
    metadata:
      labels:
        app: k8s-docker-demo
    spec:
      containers:
      - name: k8s-docker-demo
        image: ishanc2017/play-java
        ports:
        - containerPort: 8080